apiVersion: v1
kind: Service
metadata:
  name: public-app-svc
  labels:
    app: public-app
spec:
  type: LoadBalancer
  selector:
    app: public-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
